### PR TITLE
Feat: support relative media paths via config

### PR DESCRIPTION
**Pull request by awcodes**

### CODE REVIEW

**Comment by robin-dongbin** [comment]
So you realize the problem yourself now?
Just opinionated.
https://github.com/awcodes/filament-tiptap-editor/pull/133

**Comment by awcodes** [comment]
This has nothing to do with your previous PR. But if it makes you feel better about yourself then sure you were right.

**Comment by robin-dongbin** [comment]
My previous PR is because I want to use relative media  path
https://github.com/awcodes/filament-tiptap-editor/pull/133#issuecomment-1626600552

**Comment by awcodes** [comment]
I'm not going to do this with you. You're PR didn't solve the issue and was therefore not merged. You can now use your relative urls. Please feel free to write you're own plugin and do what ever you want with it. But there is zero need to bring your closed Pr into this at this time.

**Comment by Nestoran** [comment]
Would you please implement this relative path support into v2?

**Comment by awcodes** [comment]
I'm open to a PR for it, but have no plans to back port features into previous versions.

**Pull request merged**
