### PR TITLE
Feature/editor output format

### PR DESCRIPTION
**Pull request by G4b0rDev**
The TipTap Editor has 3 different output formats.
( See: https://tiptap.dev/guide/output )
I missed a option to configure in which format the editor should be output the correct format.

You can now setup the default format or for each formular field.

### CODE REVIEW

**Comment by awcodes** [comment]
This has been on the roadmap for a while now. Thank you. I'll review as soon as I can.

**Comment by awcodes** [comment]
Can you merge 1.x into your PR please and then fix any changes from there. Looks like you are changing some things that are already in 1.x

**Comment by G4b0rDev** [comment]
> Can you merge 1.x into your PR please and then fix any changes from there. Looks like you are changing some things that are already in 1.x

Sure, I wasn't sure in which branch should I create the PR.
The conflicts comes only from the builded dist assets.

**Comment by awcodes** [comment]
Hey @GaborDesigns, this all looks good to me, but I'm hesitant to do it with Enums at the moment since Filament still supports php8.0. 

Is there a way to do this without the Enums until Filament v3?

**Comment by G4b0rDev** [comment]
Hey @awcodes 🎉,

oh I forgot out, that enums are only available in php8.1.
I'm already using php8.1 with Filament v2 so I forgot the php version support for 8.0.
Sure, I've updated the output formats.

You can now use it in 3 different ways ( I updated also the docs ):
- For php8.1: Enum
- For php8.0: Constant 
- or only as string

**For php 8.1**
```php
    TiptapEditor::make('content')
        // ... other options
        ->output(FilamentTiptapEditor\Enums\TiptapOutput::Json);
```

- HTML (Format enum type: `FilamentTiptapEditor\Enums\TiptapOutput::Html`)
- JSON (Format enum type: `FilamentTiptapEditor\Enums\TiptapOutput::Json`)
- Text (Format enum type: `FilamentTiptapEditor\Enums\TiptapOutput::Text`)


**For php 8.0**
```php
    TiptapEditor::make('content')
        // ... other options
        ->output(FilamentTiptapEditor\TiptapEditor::OUTPUT_JSON);
```

- HTML (Format type: `FilamentTiptapEditor\TiptapEditor::OUTPUT_HTML`)
- JSON (Format type: `FilamentTiptapEditor\TiptapEditor::OUTPUT_JSON`)
- Text (Format type: `FilamentTiptapEditor\TiptapEditor::OUTPUT_TEXT`)


**or as string**
```php
    TiptapEditor::make('content')
        // ... other options
        ->output('json');
```

- HTML (`html`)
- JSON (`json`)
- Text (`text`)

I hope, I doens't forgot something😅

**Comment by awcodes** [comment]
Awesome. Thank you so much for doing this.

**Comment by awcodes** [comment]
hey @GaborDesigns just wanted to let you know that I had to remove the enums to keep support for php8.0, but i left everything else in.

I'll add them back for Filament v3 once support for php8.0 is dropped.

Thanks again.

**Pull request merged**
