### PR TITLE
Fix: duplication of color styles

### LINKED ISSUE #419: Source Code duplicates color in style attribute
### Filament Version

v3.2.86

### Plugin Version

v3.3.7

### PHP Version

PHP 8.2.11

### Problem description

Source Code duplicates all color values in style attribute after edit.

### Expected behavior

Don't duplicate values of style attribute.

### Steps to reproduce

1. select some text in TipTap editor
2. change text color using Color toolbar button
3. click Source Code toolbar button
4. click Confirm button
5. click Source Code again to see duplicate of color attribute

### Reproduction repository

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by awcodes**
Resolves #419

### CODE REVIEW

**Comment by mybouhssina** [comment]
@awcodes I might be missing something here, but doesn't this make the changing of color impossible? Wouldn't it make mroe sense to search and replace in the style in case it has already a color attribute?

**Comment by awcodes** [comment]
That file is reading the output from the ast it's not changing any values. The js does that.

**Comment by mybouhssina** [comment]
@awcodes could you try this please:
write a single line in the editor and set its color to red and save.
Then, refresh the page, try to set the same line to blue, save and reload the page.
Expected result: the text color is blue
Actual result: the text color is still red.

**Comment by mybouhssina** [comment]
I noticed that even the text alignment doesn t work after save.
I'm still trying to figure out how exactly the php side of Tiptap works, but I noticed that when I disabled the StyleExtension or removed its parseHTML all the problems disappear. 
Are you able to reproduce any of the problems I m talking about ? Do you want me to create a separate issue for this?

**Comment by awcodes** [comment]
Yes, please open a new issue and provide a reproduction repository. Everything is saving correctly in my demo app.

**Comment by mybouhssina** [comment]
Ok, done :)
Here is the issue: https://github.com/awcodes/filament-tiptap-editor/issues/546

**Pull request merged**
